{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "shibboleth-idp.fullname" . }}-default-deny
  labels: {{- include "shibboleth-idp.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{- include "shibboleth-idp.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "shibboleth-idp.fullname" . }}-allow
  labels: {{- include "shibboleth-idp.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{- include "shibboleth-idp.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        {{- range .Values.networkPolicy.allowedIngressNamespaces }}
        - namespaceSelector:
            matchLabels:
              {{ .labelKey }}: {{ .name | quote }}
        {{- end }}
        {{- range .Values.networkPolicy.allowedIngressPodLabels }}
        - podSelector:
            matchLabels: {{- toYaml . | nindent 14 }}
        {{- end }}
{{- end }}
