apiVersion: v1
kind: Service
metadata:
  name: {{ include "shibboleth-idp.fullname" . }}
  labels: {{- include "shibboleth-idp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "shibboleth-idp.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      # Jetty's default port. Pinned by jetty-base/start.d/http.ini in
      # the image; the helm chart treats this as a constant.
      targetPort: 8080
      protocol: TCP
