{{/*
SimpleSAMLphp wants a 32-byte secret-salt set at startup. Using lookup
gives us a stable value across upgrades; if the Secret doesn't exist yet
we generate one with randAlphaNum.
*/}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace (printf "%s-salt" (include "simplesamlphp.fullname" .)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simplesamlphp.fullname" . }}-salt
  labels: {{- include "simplesamlphp.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  salt: {{ if $existing }}{{ $existing.data.salt }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
